name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allow maintainers to manually run the workflow (useful for secret-enabled jobs)
  workflow_dispatch: {}

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run unit tests with coverage
        run: |
          # Run tests and collect coverage
          coverage run -m unittest discover -v
          coverage xml -i -o coverage.xml || true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
        if: always()

      - name: Run flake8 lint
        run: |
          flake8

  test-with-secrets:
    name: Tests (with secrets)
    runs-on: ubuntu-latest
    # Only run this job when an OPEN_WEBUI_API_KEY secret is configured in the repo
    if: ${{ secrets.OPEN_WEBUI_API_KEY != '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run UI tests that require OPEN_WEBUI_API_KEY
        env:
          OPEN_WEBUI_API_KEY: ${{ secrets.OPEN_WEBUI_API_KEY }}
          OPEN_WEBUI_API_KEY_STYLE: ${{ secrets.OPEN_WEBUI_API_KEY_STYLE }}
        run: |
          # Run only the interface UI tests which assert headers are sent
          python -m unittest -v test_interface_ui.py
