name: Secret tests

on:
  workflow_dispatch: {}

jobs:
  run-secret-tests:
    name: Run secret-enabled tests (manual)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run secret-enabled tests
        env:
          OPEN_WEBUI_API_KEY: ${{ secrets.OPEN_WEBUI_API_KEY }}
          OPEN_WEBUI_API_KEY_STYLE: ${{ secrets.OPEN_WEBUI_API_KEY_STYLE }}
          OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}
          OLLAMA_API_KEY_STYLE: ${{ secrets.OLLAMA_API_KEY_STYLE }}
        run: |
          # Run tests that validate API key behavior and any other secret-dependent tests
          python -m unittest -v test_interface_ui.py test_reasoning_engine.py
